# Generated by Django 5.2.4 on 2026-03-28 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('drivers_license_number', models.CharField(max_length=40, unique=True)),
                ('drivers_license_expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'VehicleType',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStaff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('office_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=120)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.branch')),
            ],
            options={
                'db_table': 'MaintenanceStaff',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_mileage', models.IntegerField()),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.branch')),
                ('vehicle_type', models.ForeignKey(db_column='vehicle_type_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.vehicletype')),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('rental_agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_pickup_datetime', models.DateTimeField()),
                ('scheduled_return_datetime', models.DateTimeField()),
                ('actual_pickup_datetime', models.DateTimeField()),
                ('actual_return_datetime', models.DateTimeField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=10)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.customer')),
                ('pickup_branch', models.ForeignKey(db_column='pickup_branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='pickup_agreements', to='rentals.branch')),
                ('return_branch', models.ForeignKey(db_column='return_branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='return_agreements', to='rentals.branch')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.vehicle')),
            ],
            options={
                'db_table': 'RentalAgreement',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenanceRecord',
            fields=[
                ('vehicle_maintenance_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('reported_datetime', models.DateTimeField()),
                ('issue_type', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent')], max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('InProgress', 'In Progress'), ('Complete', 'Complete'), ('AwaitingParts', 'Awaiting Parts')], default='Reported', max_length=20)),
                ('resolved_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, db_column='assigned_staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.maintenancestaff')),
                ('reporting_customer', models.ForeignKey(blank=True, db_column='reporting_customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.customer')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.vehicle')),
            ],
            options={
                'db_table': 'VehicleMaintenanceRecord',
            },
        ),
    ]
